/**
 * Ingest. Two routes in, one shape out: a directory on disk holding the source.
 *
 * The source is READ-ONLY from here on. Nothing downstream writes into it — every
 * generated byte goes to a sibling `agent-ready/` directory. That rule is what makes
 * the GitHub push safe, because the PR can then only ever ADD a folder.
 */
import fs from 'node:fs'
import path from 'node:path'
import { unzipSync } from 'fflate'

const MAX_FILES = 25_000
const MAX_BYTES = 120 * 1024 * 1024

/**
 * Only the files the audit actually reads. A real design-system repo is mostly
 * images, fixtures and lockfiles; carrying those in makes ingest slow and tells the
 * audit nothing. Anything not matched here is skipped, not rejected.
 */
const KEEP = /\.(tsx?|jsx?|mjs|cjs|css|scss|sass|less|json|md|mdx|txt|ya?ml)$/i
const SKIP_DIR = /(^|\/)(node_modules|\.git|\.next|dist-types|coverage|__snapshots__|\.turbo|\.cache|public\/images?|assets\/(img|images|fonts|video))\//i
/** Lockfiles are enormous and carry no design-system signal. */
const SKIP_FILE = /(^|\/)(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb)$/i

/** github.com/owner/repo(/tree/branch) → the pieces we need. */
export function parseRepo(url: string): { owner: string; repo: string; ref?: string } | null {
  const m = url
    .trim()
    .replace(/\.git$/, '')
    .match(/github\.com[/:]([\w.-]+)\/([\w.-]+)(?:\/tree\/([\w.\-/]+))?/i)
  if (!m) return null
  return { owner: m[1], repo: m[2], ref: m[3] }
}

/** Strip the single wrapper directory GitHub archives and most zips contain. */
function stripRoot(entries: Record<string, Uint8Array>): Record<string, Uint8Array> {
  const names = Object.keys(entries).filter((n) => !n.endsWith('/'))
  if (!names.length) return entries
  const first = names[0].split('/')[0]
  const shared = names.every((n) => n.split('/')[0] === first)
  if (!shared) return entries
  return Object.fromEntries(
    names.map((n) => [n.slice(first.length + 1), entries[n]]).filter(([n]) => n),
  ) as Record<string, Uint8Array>
}

function materialise(entries: Record<string, Uint8Array>, dest: string) {
  fs.rmSync(dest, { recursive: true, force: true })
  fs.mkdirSync(dest, { recursive: true })

  let count = 0
  let bytes = 0
  let skipped = 0
  for (const [rel, data] of Object.entries(entries)) {
    if (rel.endsWith('/') || !data.length) continue
    if (SKIP_DIR.test(`/${rel}`) || SKIP_FILE.test(rel) || !KEEP.test(rel)) {
      skipped++
      continue
    }
    // Refuse anything that would escape the destination directory.
    const target = path.resolve(dest, rel)
    if (!target.startsWith(path.resolve(dest) + path.sep)) continue
    if (++count > MAX_FILES) throw new Error(`archive has more than ${MAX_FILES} source files`)
    bytes += data.length
    if (bytes > MAX_BYTES) throw new Error('archive is larger than 120 MB of source')
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(target, data)
  }
  if (count === 0) {
    throw new Error(
      `no source files found (skipped ${skipped} non-source files). Point at a repository or folder containing the component source.`,
    )
  }
  return count
}

export async function ingestGithub(url: string, dest: string) {
  const parsed = parseRepo(url)
  if (!parsed) throw new Error('That does not look like a GitHub repository URL.')
  const { owner, repo, ref } = parsed

  const attempts = ref ? [ref] : ['HEAD']
  let lastError = ''
  for (const r of attempts) {
    const api = `https://codeload.github.com/${owner}/${repo}/zip/${r === 'HEAD' ? 'refs/heads/main' : `refs/heads/${r}`}`
    const fallback = `https://codeload.github.com/${owner}/${repo}/zip/refs/heads/master`
    for (const target of [api, fallback]) {
      const res = await fetch(target, { headers: { 'User-Agent': 'peel' } })
      if (!res.ok) {
        lastError = `${res.status} ${res.statusText}`
        continue
      }
      const buf = new Uint8Array(await res.arrayBuffer())
      const files = materialise(stripRoot(unzipSync(buf)), dest)
      return { files, name: repo, ref: r }
    }
  }
  throw new Error(
    `Could not download ${owner}/${repo} (${lastError}). Public repositories only — for a private repo, upload a zip instead.`,
  )
}

export async function ingestZip(buf: Uint8Array, dest: string, filename: string) {
  const files = materialise(stripRoot(unzipSync(buf)), dest)
  return { files, name: filename.replace(/\.zip$/i, '') }
}

/** Copy a local directory in, so the original is never touched. */
export function ingestLocal(from: string, dest: string) {
  fs.rmSync(dest, { recursive: true, force: true })
  fs.mkdirSync(dest, { recursive: true })
  let count = 0
  const copy = (src: string, out: string) => {
    for (const e of fs.readdirSync(src, { withFileTypes: true })) {
      if (e.name === 'node_modules' || e.name === '.git') continue
      const s = path.join(src, e.name)
      const d = path.join(out, e.name)
      if (e.isDirectory()) {
        fs.mkdirSync(d, { recursive: true })
        copy(s, d)
      } else {
        fs.copyFileSync(s, d)
        count++
      }
    }
  }
  copy(from, dest)
  if (!count) throw new Error('that folder contained no files')
  return { files: count, name: path.basename(from) }
}
