/**
 * POST /api/systems/:id/review — the proposed contract, before anything is written.
 *
 * This is the gate. Extraction can measure a great deal and infer the rest, but it
 * cannot know that a component is misnamed, that a variant set is wrong, or what a
 * team means by "use this instead". Ten minutes of the right person's attention here
 * is worth more than any amount of inference afterwards — which is why every serious
 * pipeline puts a human at this point, Supernova included. They just put them in
 * Figma, where it does not look like work.
 *
 * Nothing is generated by this endpoint. It reads, proposes, and marks its own
 * confidence so the reviewer knows where to look.
 */
import { NextRequest } from 'next/server'
import { extract } from '@/lib/engine/extract'
import { enrichAll } from '@/lib/generate/enrich'
import { streamResponse } from '@/lib/progress'
import { getSystem, sourceDir } from '@/lib/store'

export const runtime = 'nodejs'
export const maxDuration = 300

/** Where each field came from, so a reviewer knows what to trust. */
type Source = 'measured' | 'archetype' | 'model' | 'assumed'

export async function POST(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params
  const body = (await req.json().catch(() => ({}))) as { components?: string[] }

  return streamResponse(async (report) => {
    const row = getSystem(id)
    if (!row) return report.error('That system no longer exists.')

    const endRead = report.step('read', 'Read the source')
    const facts = extract(sourceDir(id))
    endRead(`${facts.components.length} components`)

    const available = facts.components.map((c) => c.name)
    const selected = (body.components?.length ? body.components : available.slice(0, 2)).filter((n) =>
      available.includes(n),
    )
    if (!selected.length) return report.error('Select at least one component.')

    const picked = facts.components.filter((c) => selected.includes(c.name))

    const endJudge = report.step('judge', 'Propose the contract')
    const judgments = await enrichAll(picked, facts.packageName)
    endJudge(`${picked.length} proposed · review before anything is written`)

    const proposals = picked.map((f) => {
      const j = judgments.get(f.name)
      const generated = new Set(j?.generated ?? [])

      const sourceOf = (field: string, measured: boolean): Source =>
        measured ? 'measured' : generated.has(field) ? 'model' : 'archetype'

      // Flag what a reviewer should actually look at, rather than all of it.
      const attention: string[] = []
      if (!f.docComment && generated.has('purpose')) attention.push('purpose was generated, not documented')
      if (!Object.keys(f.variants).length) attention.push('no variant axes found — confirm this component has none')
      if (f.openVariants.length) attention.push(`open variant props: ${f.openVariants.join(', ')}`)
      if (!f.exported) attention.push('not exported from the entry point')
      for (const [axis, values] of Object.entries(f.variants)) {
        if (!f.defaultVariants[axis]) attention.push(`${axis} has no declared default — "${values[0]}" would be adopted`)
      }
      if (generated.has('useInstead')) attention.push('when-NOT-to-use was generated — this is the field that decides between lookalikes')

      return {
        name: f.name,
        file: f.file,
        exported: f.exported,
        purpose: j?.purpose ?? '',
        purposeSource: sourceOf('purpose', Boolean(f.docComment)),
        aliases: j?.aliases ?? [],
        aliasesSource: sourceOf('aliases', false),
        useInstead: j?.useInstead ?? [],
        useInsteadSource: sourceOf('useInstead', false),
        variants: f.variants,
        defaultVariants: f.defaultVariants,
        props: f.props.map((p) => ({ name: p.name, type: p.type, documented: Boolean(p.description) })),
        rawValues: f.rawValues.length,
        hasMarkup: Boolean(f.markup),
        attention,
      }
    })

    report.result({ system: facts.packageName, proposals })
  })
}
